default:
  image: node:12-alpine

variables:
  BT_ENVIRONMENT: 'Sandbox'
  BT_MERCHANT_ID: 'test-merchant-id'
  BT_PUBLIC_KEY: 'test-public-key'
  BT_PRIVATE_KEY: 'test-private-key'

stages:
  - setup
  - test
  - lint
  - deploy

install:
  interruptible: true
  stage: setup
  artifacts:
    paths:
      - node_modules/
  script:
    - npm ci

info:
  interruptible: true
  stage: setup
  script:
    - npm version
    - env

test:
  interruptible: true
  stage: test
  coverage: '/Statements\s*:.*?\s+(\d+.\d+)%/'
  artifacts:
    paths:
      - coverage/
    reports:
      junit:
        - coverage/apps/invoicing-cli/junit.xml
        - coverage/apps/invoicing-graphql/junit.xml
        - coverage/apps/invoicing-web/junit.xml
        - coverage/libs/shared/junit.xml
        - coverage/libs/react-components/junit.xml
  script:
    - npm run nx -- test shared --code-coverage
    - npm run nx -- test react-components --code-coverage
    - npm run nx -- test invoicing-graphql --code-coverage
    - npm run nx -- test invoicing-web --code-coverage
    - npm run nx -- test invoicing-cli --code-coverage
    - npm run ci:coverage
  only:
    - develop
    - master
    - /^FM-\d+/
  dependencies:
    - install

# lint:
#   interruptible: true
#   stage: test
#   script:
#     - npm run nx -- lint shared
#     - npm run nx -- lint react-components
#     - npm run nx -- lint invoicing-graphql
#   only:
#     - monorepo-nx

pages:
  interruptible: true
  stage: deploy
  script:
    - mkdir -p public
    - cp coverage/*.* public/
    - mv public/index.html public/coverage.html
  artifacts:
    paths:
      - public
  dependencies:
    - test
  only:
    - develop
