default:
  image: node:12-alpine

variables:
  BT_ENVIRONMENT: 'Sandbox'
  BT_MERCHANT_ID: 'test-merchant-id'
  BT_PUBLIC_KEY: 'test-public-key'
  BT_PRIVATE_KEY: 'test-private-key'

stages:
  - setup
  - test
#  - lint

install:
  stage: setup
  artifacts:
    paths:
      - node_modules/
  script:
    - npm ci

info:
  stage: setup
  script:
    - npm version
    - env

test:
  stage: test
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  artifacts:
    paths:
      - coverage/
    reports:
      junit:
        - coverage/apps/invoicing-cli/junit.xml
        - coverage/apps/invoicing-graphql/junit.xml
        - coverage/apps/invoicing-web/junit.xml
        - coverage/libs/shared/junit.xml
        - coverage/libs/react-components/junit.xml
  script:
    - npm run nx -- test shared --code-coverage
    - npm run nx -- test react-components --code-coverage
    - npm run nx -- test invoicing-graphql --code-coverage
    - npm run nx -- test invoicing-web --code-coverage
    - npm run nx -- test invoicing-cli --code-coverage
  only:
    - monorepo-nx
    - /^FM-\d+/
  dependencies:
    - install
# lint:
#   stage: test
#   script:
#     - npm run nx -- lint shared
#     - npm run nx -- lint react-components
#     - npm run nx -- lint invoicing-graphql
#   only:
#     - monorepo-nx
