# do not use "latest" here, if you want this to work in the future
image: docker:$DOCKER_VERSION

stages:
  - setup
  #- test
  - build
  #- package
  #- deploy

variables:
  AFFECTED: ''
  DOCKER_TLS_CERTDIR: '/certs'
  DOCKER_DRIVER: overlay2
  DOCKER_VERSION: 18.09.0
  REGION: 'eu-west-1'
  AWS_REGISTRY: '918602980697.dkr.ecr.eu-west-1.amazonaws.com'
  BT_ENVIRONMENT: 'Sandbox'
  BT_MERCHANT_ID: 'test-merchant-id'
  BT_PUBLIC_KEY: 'test-public-key'
  BT_PRIVATE_KEY: 'test-private-key'

services:
  - docker:$DOCKER_VERSION-dind

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  # - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

Install Dependencies:
  stage: setup
  image: node:latest
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    # - npm version
    # - export AFFECTED_ARGS=$(./scripts/affected.sh)
    # - env
    - npm ci
  only:
    changes:
      - package-lock.json

Identify Affected:
  stage: setup
  image: node:latest
  script:
    - export AFFECTED_ARGS=$(./scripts/affected.sh)

# test:
#   interruptible: true
#   allow_failure: true
#   stage: test
#   coverage: '/Statements\s*:.*?\s+(\d+.\d+)%/'
#   artifacts:
#     paths:
#       - coverage/
#     reports:
#       junit:
#         - coverage/apps/invoicing-cli/junit.xml
#         - coverage/apps/invoicing-graphql/junit.xml
#         - coverage/apps/invoicing-web/junit.xml
#         - coverage/libs/shared/junit.xml
#         - coverage/libs/react-components/junit.xml
#   script:
#     - npm run nx -- test shared --code-coverage
#     - npm run nx -- test react-components --code-coverage
#     - npm run nx -- test invoicing-graphql --code-coverage
#     - npm run nx -- test invoicing-web --code-coverage
#     - npm run nx -- test invoicing-cli --code-coverage
#     - npm run ci:coverage
#   only:
#     - develop
#     - master
#     - /^FM-\d+/
#   dependencies:
#     - install

# lint:
#   interruptible: true
#   stage: test
#   script:
#     - npm run nx -- lint shared
#     - npm run nx -- lint react-components
#     - npm run nx -- lint invoicing-graphql
#   only:
#     - monorepo-nx

# pages:
#   interruptible: true
#   stage: deploy
#   script:
#     - mkdir -p public
#     - cp coverage/*.* public/
#     - mv public/index.html public/coverage.html
#   artifacts:
#     paths:
#       - public
#   dependencies:
#     - test
#   only:
#     - develop

Build:
  interruptible: true
  stage: build
  image: node:latest
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - ls -al ./node_modules/.bin
    - npm run affected:build -- ${AFFECTED_ARGS} --parallel --configuration production
  dependencies:
    - Install Dependencies
  artifacts:
    paths:
      - apps/*/dist
  only:
    - develop
# package_images:
#   interruptible: true
#   stage: package
#   image: docker:18
#   before_script:
#     - apk add --no-cache curl jq python py-pip
#     - pip install awscli
#     - $(aws ecr get-login --no-include-email --region "${REGION}")
#   script:
#     - docker build -t $AWS_REGISTRY/invoicing-web:$CI_COMMIT_SHA apps/invoicing-web
#     - docker push $AWS_REGISTRY/invoicing-web:$CI_COMMIT_SHA
#     - docker build -t $AWS_REGISTRY/invoicing-graphql:$CI_COMMIT_SHA apps/invoicing-graphql
#     - docker push $AWS_REGISTRY/invoicing-graphql:$CI_COMMIT_SHA
#     - docker tag $AWS_REGISTRY/invoicing-graphql:$CI_COMMIT_SHA $AWS_REGISTRY/invoicing-graphql:dev
#     - docker tag $AWS_REGISTRY/invoicing-web:$CI_COMMIT_SHA $AWS_REGISTRY/invoicing-web:dev
#     - docker push $AWS_REGISTRY/invoicing-graphql:dev
#     - docker push $AWS_REGISTRY/invoicing-web:dev
#   dependencies:
#     - build_code
#   only:
#     - develop

# deploy_dev:
#   stage: deploy
#   image: docker:18
#   dependencies:
#     - package_images
#   when: manual
#   only:
#     - develop
#   before_script:
#     - apk add --no-cache curl jq python py-pip
#     - pip install awscli
#     - $(aws ecr get-login --no-include-email --region "${REGION}")
#   script:
#     - aws elasticbeanstalk update-environment --environment-name invoicing-web-dev --version-label invoicing-web-dev
#     - aws elasticbeanstalk update-environment --environment-name invoicing-graphql-dev --version-label invoicing-graphql-dev
