image: docker:git

stages:
  - build-environment

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

build-environment:
  stage: build-environment
  image: docker:stable-dind
  rules:
    - changes:
        - Dockerfile.build
        - package.json
        - package-lock.json
        - .gitlab-ci.yml
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:build-$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:build-$CI_COMMIT_REF_NAME -f Dockerfile.build .
    - docker push $CI_REGISTRY_IMAGE:build-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:build-$CI_COMMIT_REF_NAME
