# do not use "latest" here, if you want this to work in the future
image: docker:$DOCKER_VERSION

stages:
  - setup
  #- test
  #- build
  #- package
  #- deploy

variables:
  BASH_ENV: ''
  DOCKER_TLS_CERTDIR: '/certs'
  DOCKER_DRIVER: overlay2
  DOCKER_VERSION: 18.09.0
  REGION: 'eu-west-1'
  AWS_REGISTRY: '918602980697.dkr.ecr.eu-west-1.amazonaws.com'
  BT_ENVIRONMENT: 'Sandbox'
  BT_MERCHANT_ID: 'test-merchant-id'
  BT_PUBLIC_KEY: 'test-public-key'
  BT_PRIVATE_KEY: 'test-private-key'

services:
  - docker:$DOCKER_VERSION-dind

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  # - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

Install Dependencies:
  stage: setup
  image: node:latest
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    # - npm version
    # - env
    # - npm ci --only=production
    - ./scripts/affected.sh

  only:
    changes:
      - package-lock.json
# install:
#   interruptible: true
#   stage: setup
#   variables:
#     # We are just playing with Docker here.
#     # We do not need GitLab to clone the source code.
#     GIT_STRATEGY: none
#   artifacts:
#     paths:
#       - node_modules/
#   script:
#     - npm ci

# Info:
#   interruptible: true
#   stage: setup
#   script:
#     - npm version
#     - env
# test:
#   interruptible: true
#   allow_failure: true
#   stage: test
#   coverage: '/Statements\s*:.*?\s+(\d+.\d+)%/'
#   artifacts:
#     paths:
#       - coverage/
#     reports:
#       junit:
#         - coverage/apps/invoicing-cli/junit.xml
#         - coverage/apps/invoicing-graphql/junit.xml
#         - coverage/apps/invoicing-web/junit.xml
#         - coverage/libs/shared/junit.xml
#         - coverage/libs/react-components/junit.xml
#   script:
#     - npm run nx -- test shared --code-coverage
#     - npm run nx -- test react-components --code-coverage
#     - npm run nx -- test invoicing-graphql --code-coverage
#     - npm run nx -- test invoicing-web --code-coverage
#     - npm run nx -- test invoicing-cli --code-coverage
#     - npm run ci:coverage
#   only:
#     - develop
#     - master
#     - /^FM-\d+/
#   dependencies:
#     - install

# # lint:
# #   interruptible: true
# #   stage: test
# #   script:
# #     - npm run nx -- lint shared
# #     - npm run nx -- lint react-components
# #     - npm run nx -- lint invoicing-graphql
# #   only:
# #     - monorepo-nx

# pages:
#   interruptible: true
#   stage: deploy
#   script:
#     - mkdir -p public
#     - cp coverage/*.* public/
#     - mv public/index.html public/coverage.html
#   artifacts:
#     paths:
#       - public
#   dependencies:
#     - test
#   only:
#     - develop

# build_code:
#   interruptible: true
#   stage: build
#   script:
#     - npm run nx -- build invoicing-web --prod
#     - npm run nx -- build invoicing-graphql --prod
#   dependencies:
#     - install
#   artifacts:
#     paths:
#       - apps/invoicing-web/dist
#       - apps/invoicing-graphql/dist
#   only:
#     - develop

# package_images:
#   interruptible: true
#   stage: package
#   image: docker:18
#   before_script:
#     - apk add --no-cache curl jq python py-pip
#     - pip install awscli
#     - $(aws ecr get-login --no-include-email --region "${REGION}")
#   script:
#     - docker build -t $AWS_REGISTRY/invoicing-web:$CI_COMMIT_SHA apps/invoicing-web
#     - docker push $AWS_REGISTRY/invoicing-web:$CI_COMMIT_SHA
#     - docker build -t $AWS_REGISTRY/invoicing-graphql:$CI_COMMIT_SHA apps/invoicing-graphql
#     - docker push $AWS_REGISTRY/invoicing-graphql:$CI_COMMIT_SHA
#     - docker tag $AWS_REGISTRY/invoicing-graphql:$CI_COMMIT_SHA $AWS_REGISTRY/invoicing-graphql:dev
#     - docker tag $AWS_REGISTRY/invoicing-web:$CI_COMMIT_SHA $AWS_REGISTRY/invoicing-web:dev
#     - docker push $AWS_REGISTRY/invoicing-graphql:dev
#     - docker push $AWS_REGISTRY/invoicing-web:dev
#   dependencies:
#     - build_code
#   only:
#     - develop

# deploy_dev:
#   stage: deploy
#   image: docker:18
#   dependencies:
#     - package_images
#   when: manual
#   only:
#     - develop
#   before_script:
#     - apk add --no-cache curl jq python py-pip
#     - pip install awscli
#     - $(aws ecr get-login --no-include-email --region "${REGION}")
#   script:
#     - aws elasticbeanstalk update-environment --environment-name invoicing-web-dev --version-label invoicing-web-dev
#     - aws elasticbeanstalk update-environment --environment-name invoicing-graphql-dev --version-label invoicing-graphql-dev
