version: '3.7'

services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  gateway:
    image: nginx:alpine
    expose:
      - "8001"
    hostname: gateway
    network_mode: "host"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=localhost:5432
      - ADMINER_DEFAULT_DB_NAME=postgres

  sqs:
    image: roribio16/alpine-sqs:latest
    ports:
      - 9324:9324
      - 9325:9325
