# Default values for superset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

## Set default image, imageTag, and imagePullPolicy.
image:
  repository: "916437579680.dkr.ecr.eu-west-1.amazonaws.com/iris"
  tag: "0.3.0"
  pullPolicy: "IfNotPresent"
  pullSecrets: []


## Extra environment variables that will be passed onto deployment pod
##
envVars: 
  LOG_LEVEL: 'INFO'
  SECRET_KEY: 'superset_secret'
  SQLALCHEMY_DATABASE_URI: 'superset_db_secret'

sso: 
  enabled: true
  host: 'https://sso.review.hindawi.com/auth/realms/Phenom'
  clientId: 'dev-reporting'
  clientSecret: 'client_secret'
  realmKey: 'realm_public_key'
  

## Deployment level annotations
## Useful for passing other third party annotations to interact with eg. kube2iam.
deploymentAnnotations: {}

service:
  type: NodePort
  port: 80

  ## service annotations
  annotations: {}

  ## loadbalancer source ranges. only used when service.type is "LoadBalancer"
  loadBalancerSourceRanges: []
  # - 172.31.0.0/16


ingress:
  ## If true, superset Ingress will be created
  ##
  enabled: true

  ## superset Ingress annotations
  annotations:   
    kubernetes.io/ingress.class: nginx

  ## superset Ingress hostnames
  ## Must be provided if Ingress is enabled
  ##
  host: reporting.dev.phenom.pub

  ## superset Ingress TLS configuration
  ## Secrets must be manually created in the namespace
  ##
  tls: []
  #   - secretName: superset-server-tls
  #     hosts:
  #       - superset.domain.com

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
tolerations: []

## Affinity and anti-affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
#  requests:
#    cpu: 50m
#    memory: 256Mi
#  limits:
#    cpu: 500m
#    memory: 750Mi

## Configure liveness/readiness params
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 80
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 2
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 2
