variables:
  DOCKER_REPO: $CI_ECR_URL
  DOCKER_REPO_REVIEW: $REVIEW_ECR
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  #DOCKER_HOST: tcp://docker:2375/
  #DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

services:
  - docker:18.09.7-dind

stages:
  - build
  - test
  - push
  - deploy
  - regression

build:
  image: docker:18.09.7
  stage: build
  only:
    - merge_requests
    - develop
    - staging
    - master
  except:
    - schedules
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG

lint:
  image: $DOCKER_IMAGE_TAG
  stage: test
  only:
    - merge_requests
    - develop
    - staging
    - master
  except:
    - schedules
  variables:
    GIT_STRATEGY: none
  script:
    - cd ${HOME}
    - npm run lint

test:
  image: $DOCKER_IMAGE_TAG
  stage: test
  only:
    - merge_requests
    - develop
    - staging
    - master
  except:
    - schedules
  variables:
    GIT_STRATEGY: none
  script:
    - cd ${HOME}
    - npm run test

push:qa:
  image: docker:latest
  stage: push
  only:
    - develop
  except:
    - schedules
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $DOCKER_IMAGE_TAG
    - docker tag $DOCKER_IMAGE_TAG $DOCKER_REPO:$CI_COMMIT_SHA
    - export AWS_REGION="eu-west-1"
    - export AWS_DEFAULT_REGION="eu-west-1"
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - apk update
    - apk --no-cache add --update curl python python-dev py-pip
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:/usr/bin/:$PATH
    - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
    - docker push $DOCKER_REPO:$CI_COMMIT_SHA
    - docker tag $DOCKER_REPO:$CI_COMMIT_SHA $DOCKER_REPO:latest
    - docker push $DOCKER_REPO:latest

push:demo:
  image: docker:latest
  stage: push
  only:
    - staging
  except:
    - schedules
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $DOCKER_IMAGE_TAG
    - docker tag $DOCKER_IMAGE_TAG $DOCKER_REPO:$CI_COMMIT_SHA
    - export AWS_REGION="eu-west-1"
    - export AWS_DEFAULT_REGION="eu-west-1"
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - apk update
    - apk --no-cache add --update curl python python-dev py-pip
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:/usr/bin/:$PATH
    - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
    - docker push $DOCKER_REPO:$CI_COMMIT_SHA
    - docker tag $DOCKER_REPO:$CI_COMMIT_SHA $DOCKER_REPO:demo
    - docker push $DOCKER_REPO:demo

push:production:
  image: docker:latest
  stage: push
  when: manual
  only:
    - master
  except:
    - schedules
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $DOCKER_IMAGE_TAG
    - docker tag $DOCKER_IMAGE_TAG $DOCKER_REPO_REVIEW:$CI_COMMIT_SHA
    - export AWS_REGION="eu-west-1"
    - export AWS_DEFAULT_REGION="eu-west-1"
    - export AWS_ACCESS_KEY_ID=$REVIEW_AWS_ACCESS
    - export AWS_SECRET_ACCESS_KEY=$REVIEW_AWS_SECRET
    - apk update
    - apk --no-cache add --update curl python python-dev py-pip
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:/usr/bin/:$PATH
    - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
    - docker push $DOCKER_REPO_REVIEW:$CI_COMMIT_SHA
    - docker tag $DOCKER_REPO_REVIEW:$CI_COMMIT_SHA $DOCKER_REPO_REVIEW:production
    - docker push $DOCKER_REPO_REVIEW:production

deploy:qa:
  image: docker:latest
  stage: deploy
  only:
    - develop
  except:
    - schedules
  variables:
    EB_ENV: qa-review
    EB_VERSION: qa-review
    GIT_STRATEGY: none
  environment:
    name: qa
    url: https://qa.review.hindawi.com
  script:
    - export AWS_REGION="eu-west-1"
    - export AWS_DEFAULT_REGION="eu-west-1"
    - export AWS_ACCESS_KEY_ID=$REVIEW_AWS_ACCESS
    - export AWS_SECRET_ACCESS_KEY=$REVIEW_AWS_SECRET
    - apk update
    - apk --no-cache add --update curl python python-dev py-pip
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:/usr/bin/:$PATH
    - aws elasticbeanstalk update-environment --environment-name $EB_ENV --version-label $EB_VERSION

deploy:automation:
  image: docker:latest
  stage: deploy
  only:
    - develop
  except:
    - schedules
  variables:
    EB_ENV: automation-review
    EB_VERSION: qa-review
    GIT_STRATEGY: none
  environment:
    name: automation
    url: https://automation.review.hindawi.com
  script:
    - export AWS_REGION="eu-west-1"
    - export AWS_DEFAULT_REGION="eu-west-1"
    - export AWS_ACCESS_KEY_ID=$REVIEW_AWS_ACCESS
    - export AWS_SECRET_ACCESS_KEY=$REVIEW_AWS_SECRET
    - apk update
    - apk --no-cache add --update curl python python-dev py-pip
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:/usr/bin/:$PATH
    - aws elasticbeanstalk update-environment --environment-name $EB_ENV --version-label $EB_VERSION

deploy:demo:
  image: docker:latest
  stage: deploy
  only:
    - staging
  except:
    - schedules
  variables:
    EB_ENV: demo-review
    EB_VERSION: demo
    GIT_STRATEGY: none
  environment:
    name: demo
    url: https://demo.review.hindawi.com
  script:
    - export AWS_REGION="eu-west-1"
    - export AWS_DEFAULT_REGION="eu-west-1"
    - export AWS_ACCESS_KEY_ID=$REVIEW_AWS_ACCESS
    - export AWS_SECRET_ACCESS_KEY=$REVIEW_AWS_SECRET
    - apk update
    - apk --no-cache add --update curl python python-dev py-pip
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:/usr/bin/:$PATH
    - aws elasticbeanstalk update-environment --environment-name $EB_ENV --version-label $EB_VERSION

deploy:production:
  image: docker:latest
  stage: deploy
  when: manual
  only:
    - master
  except:
    - schedules
  variables:
    EB_ENV: production
    EB_VERSION: production
    GIT_STRATEGY: none
  environment:
    name: production
    url: https://review.hindawi.com
  script:
    - export AWS_REGION="eu-west-1"
    - export AWS_DEFAULT_REGION="eu-west-1"
    - export AWS_ACCESS_KEY_ID=$REVIEW_AWS_ACCESS
    - export AWS_SECRET_ACCESS_KEY=$REVIEW_AWS_SECRET
    - apk update
    - apk --no-cache add --update curl python python-dev py-pip
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:/usr/bin/:$PATH
    - aws elasticbeanstalk update-environment --environment-name $EB_ENV --version-label $EB_VERSION

cypress-e2e:qa:
  image: cypress/base:10
  stage: regression
  allow_failure: true
  only:
    - schedules
  script:
    - pwd
    - yarn
    - yarn run ci:test-e2e-dev
  artifacts:
    when: always
    paths:
      - /builds/hindawi/xpub/xpub-review/packages/hindawi-e2e/cypress/videos/**/**/*.mp4
      - /builds/hindawi/xpub/xpub-review/packages/hindawi-e2e/cypress/screenshots/**/**/*.png
    expire_in: 1 day
