version: '3.7'

services:
  postgres:
    image: psql12:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/reporting:/var/lib/postgresql/data

  windowssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
