version: '2.0'
services:
  sns:
    image: s12v/sns
    ports:
      - '9911:9911'
    volumes:
      - ./src/config/db.json:/etc/sns/db.json
    depends_on:
      - sqs
  sqs:
    image: s12v/elasticmq
    ports:
      - '9324:9324'
